### ISSUE TITLE
system.config validation

### ISSUE THREAD

**Issue by zippy** [metacurrency/holochain#10]
validate system config on startup, i.e. you have to choose at least one of the peer operating modes (or warnings thereof)

**Comment by GerryG** [comment]
This is for author vs. node modes, right? Seems that default is author mode. Am I right in thinking that only the nodes have permanent storage for chains? In other words, you have to publish from an author mode instance to a node for it to be distributed.

**Comment by zippy** [comment]
Yes, that's what this ticket was intended for.

Well, there are two different kinds of "storage" one is storage of the full chains themselves, which only Author nodes MUST do.  The other is storage of data published to the DHT which DHT nodes must do.  We don't have the nomeclature down perfectly here, and need to improve it, but both types are nodes, but one type is where you add entries to chains according to the validation rules, and the other type is where you serve DHT put/get requests of chain entry data (and also run validation rules to confirm integrity)
