### ISSUE TITLE
Implement API keys for Inter-Chain calling

### ISSUE THREAD

**Issue by artbrock** [metacurrency/holochain#110]
Suppose a holochain wants to call a function in another specific holochain (to lookup something, or maybe even commit something). Should we use the localhost as a bridge, such that both chains need to be installed locally (Art think yes for a truly distributed approach)?  Use more centralized dns-ed gateways? For local calls should we add hidden symlinks in the .holochain directory in form: .QmlASi...0sd8 such that an app can call a function in another app that it knows the DNA hash for (since it could be named differently locally)?

**Comment by christopherreay** [comment]
if we know the dna hash of the other chain, then we can use a dynamic
calling strategy defined by the app, defaulting to "download and local"

**Comment by artbrock** [comment]
We may be able to use the same kind of token / permissions system as for the capabilities tokens for accessing private data.
