### ISSUE TITLE
Dev Coord-Call 3/21/17

### ISSUE THREAD

**Issue by zippy** [metacurrency/holochain#113]
[Minutes here](https://hackmd.io/CYRmFZxAzBOBaAbNA7AJngFgKYA4DM8AhmgAwrwogoDGARikSHmkUA==)

agenda:
- [x] check-in/roll call
- [x] reports/demos
- [x] requests
- [x] waffling
- [x] flagging breaking things...

**Comment by timotree3** [comment]
- [ ] Create a checkbox

**Comment by matthewjosef** [comment]
REPORTS / DEMOS
Docker Highlights:
- [ ] we can have holochain apps in our docker file (on build function).  Could run people's init stuff for them.
- [ ] Going to be breaking 109 chain

**Comment by timotree3** [comment]
Merged #112

**Comment by matthewjosef** [comment]
Agenda with checkboxes managed in Github Issues.
Hackmd is where we keep minutes (see link above)
for now, meetings are held at http://ceptr.org/devchat
