### ISSUE TITLE
Trying to run holochain just makes it, runs the tests and exits

### ISSUE THREAD

**Issue by TrevorHilder** [metacurrency/holochain#118]
Hi folks,

README.md is wrong for Docker Installation, because it neglects to specify:
   mkdir holochain
   cd holochain
before git clone, then says cd holochain after git clone.

You have a problem with Dockerfile, because it ends with:
   CMD ["make", "test" ]
so when you run the container, that is exactly what it does.

I am a newbie to docker and to holochain, but I can see there is something wrong here!

Regards,
  Trevor

**Comment by zippy** [comment]
@christopherreay , is this because the right stuff hasn't yet been merged to master?

**Comment by christopherreay** [comment]
AYe. Theres a load of stuff not mergeed into master

**Comment by timotree3** [comment]
It seems I didn't see the `.` at the end of that clone command. Fixing it now.
