### ISSUE TITLE
Dev-Coord Call: 3/28/17

### ISSUE THREAD

**Issue by zippy** [metacurrency/holochain#123]
----
AGENDA - [Online Meeting](http://ceptr.org/devchat) - [Minutes](https://hackmd.io/CYRmFZxAzBOBaAbNA7AJngFgKYA4DM8AhmgAwrwogoDGARikSHmkUA==?edit)
- [x] Clearing
- [x] Any Warnings about Changes which Break Things
- [x] Reports on work / Demos of cool progress
- [x] Requests for other Team Members
- [x] Updating Waffle Issues

---

**Comment by christopherreay** [comment]
Yey. I made it :) Coffee abound. It is really good to speak with everyone
