### ISSUE TITLE
Epic -- Better Code Organization

### ISSUE THREAD

**Issue by GerryG** [metacurrency/holochain#140]
Clearly separate concerns in the code, including but not limited to:

1. DHT Storage
2. Local Chain Storage
3. Agents -- Key infrastructure, private key handling and signing need to be modular
4. Application Code/Interfaces
5. - Nucleus - Initialization, registration and loading dna
6. - Nucleus APIs - JS and Zygo now, want a 'bare' nucleus with Go APIs
7. - Zomes, EntryDefs and Functions
9. Signing Callback API so that Agents can be externally managed.

**Comment by zippy** [comment]
As an epic it's fine to keep things this kind of ticket in backlog, and then break it into specific tickets which get moved into prioritized and then in-progress...

**Comment by GerryG** [comment]
Sounds good to me. Link to existing issues that are within the scope as #141

**Comment by GerryG** [comment]
I think what I want to take up next is at point 7. I think your actions part is connected to 5 and 6, really 6 more, but clarifying the 5/6 boundary shouldn't be done until you've finished and merged.

**Comment by zippy** [comment]
As per 5/2 coord-call re making issues be  atomic immediate-term and using milestones for longer term stories, I'm closing this ticket for now.  Please feel free to add back particular well-described smaller tickets, such that someone could take the ticket and start working on it.

**Comment by GerryG** [comment]
I think I added at least one for the subtasks, I will add others as I work on them and get them ready to be mergable.
