### ISSUE TITLE
Refactor -- Actions

### ISSUE THREAD

**Issue by zippy** [metacurrency/holochain#141]
abstract the aspects associated with a function available to all nuclei into an "Action," i.e. validation, additions to chain/dht.

Currently these are spread across a bunch of files and adding a new action as I'm doing in #55 requires touching all of them.  This refactor should allow adding functional and data definitions for the different aspects to be defined in one place.

This may also subsume #53

**Comment by GerryG** [comment]
I think this addresses at least one of the points I put in the Issue I just added.

**Comment by zippy** [comment]
yep

**Comment by GerryG** [comment]
I really would like to work on this one. I know it will make you nervous but I promise to make sure I'm working according to your architecture plan if I do.

This is so you can have the bits that are more or less the same in all nuclei be the shared? Or that would be a way to do this? I have some ideas I'd like to try.

**Comment by zippy** [comment]
No, not so much, that's already refactored out, i.e. it's at the bottom of holochain.go.  This ticket is about making it easy to add a new function to a nucleus, and since I have a bunch of functions to add in #55 and since I've added enough of them already, I see the pattern of what's common and what's not, so it's time to refactor that out.  

My plan, and what I've already started coding today, is an  Action interface that defines all the necessary functions and data that get used by the machinery in dht.go and validate.go, etc for the different phases that happen as a result of an action getting fired off from the nucleus.

Is that what you were planning?

**Comment by GerryG** [comment]
You are maybe accomplishing a different goal that I have in mind, but for sure I will wait until your work on this one is merged before thinking to deeply and changing code for my needs.

So, if I'm adding tickets that are close to work you have in progress or soon to be, it will help us not collide and make merges easier.

**Comment by zippy** [comment]
Sounds good.  That's actually also why I added this ticket on work I was in progress on, because I realized it was close to work you wanted to do, and I wanted to make that visible, i.e. not hide the refactor under #55, but motivate it from #55.

**Comment by GerryG** [comment]
Very good, keep me posted on progress, I'm sure I'll see when it merges.
