### ISSUE TITLE
Refactor to be able to Set and Handle a WireType Setting for Chains

### ISSUE THREAD

**Issue by GerryG** [metacurrency/holochain#143]
I started working on this and realized it really needs more change that expected to function definitions and such. I think we can and should do this way before there is any pressure to actually implement a new wire type. Let's get the internal APIs and structures ready so we are less likely to need "breaking changes" to implement a JSON wire format (for example)

I think I will squirrel away the WIP on a branch and we can take a look at it and discuss.

**Comment by zippy** [comment]
closed for now, if there is a use-case that drives this refactor we will reopen.

**Comment by GerryG** [comment]
Just to remind me what I was thinking now. I think we still want to be able to support a different wire format (not changing it), but that should be configured on the right objects that relate to wire formatting (dht related gossip, node, etc. code). We still want to shift to a different one at some point and having it refactored to support a configuration parameter will help towards that.
