### ISSUE TITLE
exported functions code cleanup

### ISSUE THREAD

**Issue by zippy** [metacurrency/holochain#146]
Currently most functions in the holochain name space start with a capital letter indicating that they are exported.  This is probably wrong, and needs to be thought through more carefully.

As side effect is that this will decrease the large number of errors we are getting from golint

**Comment by GerryG** [comment]
Are you already doing this?
I was thinking this could be combined with generally organizing where the methods are. It isn't good to do that kind of re-org a lot because it complicates merges. We need to coordinate this with my already outstanding "basic refactors"

**Comment by zippy** [comment]
I'm not doing this, that's why it's in the backlog.  What ever I'm actually doing is always in "In Progress" on the waffle.  I think it's better to not combine things, but separate them into discrete tasks.

**Comment by GerryG** [comment]
Maybe done in sequence is better than together, which is more or less what I mean. If/when I do more moving of code, it may be a convenient time to review public vs. private.

I'm still getting the hang of the team tools and how to know about priority. I guess backlog is "unmarked" in the issue view.

**Comment by zippy** [comment]
superseded by #208
