### ISSUE TITLE
hc gen from <source> <name>

### ISSUE THREAD

**Issue by zippy** [metacurrency/holochain#15]
should copy configuration files

Is this cloning to a new instance or joining?

**Comment by GerryG** [comment]
This isn't in the hc usage message either. First thing you find when you load and init is it saying no dna.conf file. Presumably I have to clone one to get started, but how?

**Comment by zippy** [comment]
yep, if you see in the history of this ticket we've changed the command to "gen from <SOURCE>" which isn't implemented yet.

For now, you have to use 'gen dev'  followed by 'gen chain' to get something workin.
