### ISSUE TITLE
Implement DHT configuration options in DNA file

### ISSUE THREAD

**Issue by artbrock** [metacurrency/holochain#151]
I've documented a bunch of DNA settings we intend to implement, but haven't built yet. See [details in wiki](https://github.com/metacurrency/holochain/wiki/DNA-Reference#dht).

**Comment by GerryG** [comment]
wiki link is 404, is that a link or site problem?

**Comment by zippy** [comment]
basic feature and first option implemented, remaining settings to be added during DHT Upgrades Milestone phase.
