### ISSUE TITLE
track all the sources that put the same hash to the dht

### ISSUE THREAD

**Issue by zippy** [metacurrency/holochain#166]
In many cases multiple source chains will commit the same entry and push it to the DHT.  It needs to track all the different sources that have made those puts/mods etc..  This probably means we need to track status by source.

**Comment by christopherreay** [comment]
how can multiple sources produce the same hash? do you mean independently? or through some synchronised layer?

**Comment by zippy** [comment]
It's very easy to add the same entry onto your chain as someone else has.  The header of the entry will always be different (different user keys and timestamps etc), but the entry itself could easily be the exact same because it could be as simple as a single word which would hash to the same value for everyone.  This is an app design question.  If you need all entries to be different  on everyone's chain, then you need to include "uniqueifying" values in the entry.

**Comment by lucksus** [comment]
see also #409
