### ISSUE TITLE
Design scaffolding engine

### ISSUE THREAD

**Issue by artbrock** [metacurrency/holochain#170]
Document questions and structure for generating a JSON scaffold file to generate an app which only needs final logic coding to be complete.

**Comment by zippy** [comment]
https://docs.google.com/spreadsheets/d/1DI53K65f5Mj4xDD_9xOe7NDVd1xq4szTTzZII4C0DsA/edit

**Comment by christopherreay** [comment]
Cheers

**Comment by artbrock** [comment]
Redesigned with Nico's feedback to do a  Quick Start scaffold for geeks, followed by the app wizard to go into more detail. Quick start should be finished this week.

App Wizard in another week or two.
