### ISSUE TITLE
Build Scaffold UI

### ISSUE THREAD

**Issue by artbrock** [metacurrency/holochain#171]
Build a web-based holochain app wizard which outputs a scaffold.json file for generating an app (or 80% of an app) which only needs final logic coding.

**Comment by christopherreay** [comment]
https://github.com/metacurrency/hc-scaffold

**Comment by artbrock** [comment]
Prototype is growing here: 
http://xagasoft.com/~neonphog/hc-scaffold/dist/

**Comment by zippy** [comment]
The scaffold app is now working and tickets on it are in their own board: https://waffle.io/metacurrency/hc-scaffold
