### ISSUE TITLE
End-to-End Crypto available within a Holochain

### ISSUE THREAD

**Issue by matthewjosef** [metacurrency/holochain#189]
- [ ] implement option in DHTConfig for end-to-end encryption
- [ ] add encryption public key to genesis block when selected, and also auto-put at genesis time
- [ ] added getkey message to get the public key associated with the node address that happens in the clear before encryption
- [ ] add a cache of public keys. (maybe handled by libp2p).
- [ ] add encryption to all messaging in node.go

**Comment by zippy** [comment]
From what I can tell LibP2P is already handling this for us.  I'm not sure we need to re-add this layer in.  https://github.com/libp2p/go-libp2p-interface-conn/blob/master/interface.go   search for EncryptConnections,  then look at https://github.com/libp2p/go-libp2p-conn/search?utf8=%E2%9C%93&q=EncryptConnections&type=

**Comment by zippy** [comment]
One trivial way to confirm this is to just use wireshark or something like that to inspect the packets to confirm that things aren't going in the clear.  @timotree3 would you enjoy doing that?

**Comment by artbrock** [comment]
Dayzee has been getting clearer about what and how libP2P does this.... It does look like it can do it, but it couldn't hurt to test it.

**Comment by christopherreay** [comment]
* libp2p encrypts all messages sent over the wire.
* messages are encrypted end to end regardless of the number or complexity of the transports in between.
* the actual *content* of the messages are not encrypted from the point they arrive "in memory" of the recipient
