### ISSUE TITLE
Discuss if #174 is prerequisite for 171,2,3 and 5. Nope. :) Discuss further architechture designs

### ISSUE THREAD

**Issue by christopherreay** [metacurrency/holochain#196]
#174 

#171 
#172 
#173 
#175

**Comment by christopherreay** [comment]
Without a package manager, any updates to the core create a completely unmanaged route to update. Therefore there is no value in creating "web" interfaces, or any other tools that are specifically aimed at people without sysadmin skills

**Comment by christopherreay** [comment]
#199

**Comment by christopherreay** [comment]
Alternative architecture discussion

Push out dependency on libp2p into a service
Equinox
spiderweb synchronous protocol
* also for synchronous contracts
central holochain for hash state guarantee

**Comment by zippy** [comment]
All of this stuff will actually happen at the same time and be integrated, see also #204
