### ISSUE TITLE
Integrate Holoskel's multi-node testing into Scaffold engine

### ISSUE THREAD

**Issue by zippy** [metacurrency/holochain#202]
currently Holoskel is our scaffold, and the expectation is that you would start editing the dna/ui files after doing a git clone.  Really app development will proceed by generating the 80% app from the scaffold.json.

**Comment by christopherreay** [comment]
Aye, ive kind of been expecting this issue to appear at some point. Obvisouly im on hand to help out.

Various caveats are:
Whilst this system of Scripts etc *works*, its not the best way by any means of achieving the functionality.  I assume that  #174 will be involved at some point

**Comment by zippy** [comment]
Exactly, it's kind of like a wizard.  Here's Art's spreadsheet doc: https://docs.google.com/spreadsheets/d/1DI53K65f5Mj4xDD_9xOe7NDVd1xq4szTTzZII4C0DsA/edit  (also in #170)

**Comment by zippy** [comment]
Here' the current plan:  Assume that the current holochain repo will evolve into being the full dev repo, and that we will create a separate repo with a streamlined app for end-users.  We can use: something like https://equinox.io/docs  for a lightweight (or an electron app)  that doesn't have test/stuff and is bundled with the HCoHC and is about installing and running built apps. 

This mean we can move scripts in HoloSkel into the current repo so they can be used with all the sample apps.

**Comment by zippy** [comment]
now part of #204
