### ISSUE TITLE
make hc test return exit code 1 if any tests fail

### ISSUE THREAD

**Issue by christopherreay** [metacurrency/holochain#211]

**Comment by timotree3** [comment]
There is a duplicate issue of this that has been resolved. https://github.com/metacurrency/holochain/issues/93

**Comment by christopherreay** [comment]
oh right, so it's my fault for ignoring the return value. cool. cheers

**Comment by timotree3** [comment]
If you're saying this has already been fixed then please close this issue.

**Comment by christopherreay** [comment]
oh I'm sorry, I fell asleep
