### ISSUE TITLE
Modification of ~/.bashrc in install scripts

### ISSUE THREAD

**Issue by timotree3** [metacurrency/holochain#213]
Currently the scripts in the `bin` folder modify the users `~/.bashrc` there are a number of flaws in this, it assumes the user is using bash, but also it's not okay to modifiy that file inside of a bash script, especially not without warning the user.

If the point of this change is the allow easy shell completion, then make the completion scripts available and give the user the choice of sourcing them in their `~/.bashrc`.

**Comment by christopherreay** [comment]
umm. I guess could build a holochain script that passes all the commands
through to the scripts as they are, and add the completion to
bash_completion.d

same difference, done proper. it all works anyway so no biggy

**Comment by christopherreay** [comment]
ln the single script into /usr/bin or whatever and add completion for that
too

**Comment by timotree3** [comment]
It sounds like you're taking on this issue, want me to assign you?

**Comment by christopherreay** [comment]
yah I can do that. it's all in my head anyway

**Comment by zippy** [comment]
I'm not so sure it's a problem to modify the bashrc. It's a pretty common thing to do when dev tools are installed. When I look at my own .bashrc I see stuff that was auto added to it by both NVM, RVM and Travis.  It is nice to add a comment that says who (i.e. which tool) added it though!

**Comment by zippy** [comment]
But the real reason for modifying the bashrc is not because of the completion, but to make the bin directory part of the path so you can just run the scripts.  This is the same reason other projects do it, is to make the tools available without having to install them outside the user's space.

**Comment by christopherreay** [comment]
We could ask Noam Chomsky to Arbitrate for us?

**Comment by zippy** [comment]
closing this because eventually these will be migrated into a go cmd

**Comment by christopherreay** [comment]
hmm. how do you install stuff in the windows path? who cares? I don't :)
