### ISSUE TITLE
organise an event to which we invite Noam Chomsky, and he actually comes

### ISSUE THREAD

**Issue by christopherreay** [metacurrency/holochain#214]

**Comment by timotree3** [comment]
This ticket doesn't seem at all relevant to this repository. Maybe it would be more relevant in a personal todo-list/kanban.

Is there a way in which this ticket relates to our holochain implementation?

**Comment by christopherreay** [comment]
You better close it then Timo
ᐧ

Be prepared to have your predictions come true

**Comment by artbrock** [comment]
I've put it in my personal Kanban to track it with business and community activities, and I'm going to close this from the code repo.

**Comment by christopherreay** [comment]
that's much better
