### ISSUE TITLE
Break out examples into separate repos

### ISSUE THREAD

**Issue by artbrock** [metacurrency/holochain#240]
Clutter, Cludder, and Holochat should be broken out into separate sub-projects with their own issues, roadmap, feature requests, etc. separate from the main holochain repo.

Figure out how to manage the sub-projects in the repo appropriately (versioning, etc.)

**Comment by zippy** [comment]
wip on this happening over at: https://github.com/holochain/  Now we just need to figure out when to remove the examples, or if we still include them but as git sub-projects from those repos.

**Comment by christopherreay** [comment]
or also import possibly import them into examples at milestones, which leaves the organisation "Holochain" more open to mistakes etc

**Comment by zippy** [comment]
the nice thing about git sub-projects, I think, is that you manually have to do just that, i.e. what you include in one project is a the other project at a given commit, i.e. it doesn't automatically fast-forward.

**Comment by christopherreay** [comment]
I thought you could update the sub projects recursively with a git command. either way the design idea is clearly the same

**Comment by christopherreay** [comment]
yes. I think you're right. https://stackoverflow.com/questions/1777854/git-submodules-specify-a-branch-tag

I think that people could still manually update sub modules from within their directories which is a bug/feature

also when downloading the repo, I think the clone would not populate the sub modules until a git submodule --init is called. 

since we don't need need any features, and we want to exactly pin versions of the examples to versions of the core, I might err towards hard coding them still.. ?

**Comment by artbrock** [comment]
Maybe we don't even need to have example apps included in the holochain code itself, and instead point to where they can be found. Since it is somewhere between possible and likely that they won't all be kept up to date with changing underlying infrastructure, we should have probably the directory app filter for compatibility. :laughing:

**Comment by christopherreay** [comment]
well obviously

**Comment by christopherreay** [comment]
(lol)

**Comment by zippy** [comment]
task is to remove the entire directory,  complete adding apps (cludder,cointoss), changing main README

**Comment by zippy** [comment]
also to make sure any docs that refer to the "examples" directory get updated

**Comment by zippy** [comment]
added cludder

**Comment by zippy** [comment]
Need to write a script which runs through all the examples in the holochain repo and tests them against current version holochain/master.  @christopherreay wanna do this?  I'm ok that it's not automatic, or part of travis for now, but we should just have it...

**Comment by zippy** [comment]
Now that #304 and #305 are at pull request state, this is almost done.  One missing part is that #279/#309 test for scenarios rely on the examples directory existing, thus to complete this ticket it needs to be changed to read the "canonical" internal test app, which doesn't actually have any scenario tests in it yet... This has been added as ticket #328
