### ISSUE TITLE
As cointoss user I want to see the history of coin tosses with any given handle

### ISSUE THREAD

**Issue by zippy** [metacurrency/holochain#251]
To complete the demo, the cointoss app should:
- [ ] add a tossResult entry type that the players commit at the end of the handshake so you don't have to use N2N every time to see the final outcome using confirmToss
- [ ] add a tosses linking entry to be able to get (and render) tosses that a player has made in the past

**Comment by zippy** [comment]
I did this and I was up and running: 
```
$ hcdev init -cloneExample cointoss cointoss
git: Cloning into 'cointoss'...

cloning cointoss from github.com/Holochain/cointoss
$ cd cointoss/
$ hcdev web
Copying chain to: /home/eric/.holochaindev
validate commit: handle
validate put: handle
eric@isotopy is QmNmWdNWNfdQ5yMb1pKbtNasziFEbipXiF6ADj1yUN55Uw
validate commit: handle_links
validate link: handle_links
validate commit: directory_links
validate link: directory_links
Serving holochain with DNA hash:Qme2iTS9Ev6CNVXK6i4CJtFSM1YAgE2u9Gt5rzQaUF9EBS on port:4141

...
```

Two thing I noticed: 1) the ui doesn't reload past tosses at startup, which would be nice.   2) setting the handle by clicking on it brings up the window, but it's not actually working, or it's working intermittently...  I think I didn't pay careful attention to that when I put it together as I was focusing on the cointoss part.  I copied it from holochat...

**Comment by rayzer42** [comment]
possible HC version conflict. Pull and try now?
