### ISSUE TITLE
Documentation on the README.md gives no indication of how to install holochain

### ISSUE THREAD

**Issue by christopherreay** [metacurrency/holochain#260]
Have a look and tell me if Im mad. 

The readme, for "go installation" explains how to install go, and then starts talking about using hc. I cant see anything about downloading or `make`ing hc

?

**Comment by zippy** [comment]
Your mad, I see this:

Go Based Install

Install Go on your system. See platform specific instructions and hints below for making this work.
Install the hc command line tool with:
$ go get -d github.com/metacurrency/holochain
$ cd $GOPATH/src/github.com/metacurrency/holochain
$ make
Test that it works (should look something like this):
$ hc -v
hc version 0.0.x (holochain y)

That seems like 1,2,3 instructions to mee!

**Comment by christopherreay** [comment]
oh I was looking at it from the perspective of trying to develop on the core.

I had to work it all out my tiny self.

I've made comments on the 204 branch pull request about it actually
