### ISSUE TITLE
make bs fails

### ISSUE THREAD

**Issue by christopherreay** [metacurrency/holochain#262]
go get github.com/metacurrency/holochain/cmd/bs
# github.com/metacurrency/holochain
./gossip.go:186: undefined: sort.Slice
Makefile:40: recipe for target 'bs' failed
make: *** [bs] Error 2

**Comment by zippy** [comment]
version number issue, see https://github.com/metacurrency/holochain/commit/6b6304ab318d52d838fd59475914618f222035ef
I think you just have to update to go 1.8

**Comment by christopherreay** [comment]
YEP
