### ISSUE TITLE
Exploring using a kademlia DHT as the base for holochain DHT

### ISSUE THREAD

**Issue by christopherreay** [metacurrency/holochain#263]
* Kademlia white paper
  * https://pdos.csail.mit.edu/~petar/papers/maymounkov-kademlia-lncs.pdf
* go implementation of a kademlia DHT on top of libp2p
  * https://github.com/libp2p/go-libp2p-kad-dht

Implement a standalone KadDHT node accessible by socket / xmlrpc / OS pipes
its expected that the standalone DHT node will implement:
* Put and Get messages
* routing by peer id (hash of public key)
* end to end encryption between nodes
* automated peer discovery and network address layer information discovery as a by product of message passing
* bootstrapping is a natural effect of the kademlia architechture as long as nodes know to communicate a PING to the fixed IP bootstrap servers when they come online
* relaying node to node to node of messages
* NAT punching on top of a distributed p2p architecture
  * for full coverage we can use the bootstrap servers as stun servers
  * and we should probably set the bootstrap servers (at least) as relay servers, again, for full coverage of the network in all conditions.
* automated neighbourhood development and intra-neighbourhood gossip?

Testing will have to include:
  - [ ] various DHT get and put methods
    - [ ] TODO: details
    - [ ] potentially use messages to schedule NATing, though this may be unecessary
    - [ ] validation packages
  - [ ] NAT traversal
    - [ ] using P2P
    - [ ] using STUN@bootstrap
  - [ ] firewall traversal using relay@???

As a standalone KadDHT node exectuable, which can be accessed by a holochainNode:
  * potentially there may be some Holchain DHT node information stored on the holochainNode or added as customisation to the KadDHT node (it is pretty standard practice to modify the existing KadDHT code for custom situations. I would suggest the more data that can be kept in the holochainNode app, rather than altering the source of the KadDHT, the better.
  * as the most secure solution, probably socket communication between the holochainSourceChain and the DHT node.
  * There appears to be the potential to run multiple DHT nodes in the one KadDHT runtime, given the architechture of libp2p's multi-multiplexing, which may produce efficiency savings, and could be useful in the "apple scenario". However efficiency savings I would expect to be minimal. There may be some kind of structure reason that this would be a better solution than running a separate KadDHT Node for each Holochain

# notes
It is not immediately obvious how the "uniqness" of DNA applies to maintaining purity of the network. I cant see any endemic solution to this built into the existing framework. I suggest that the DNA includes a private key, and that ALL communications are encrypted using the public key of the DNA before leaving the source chain to enter the DHT network. On this basis any code would have to have the actual DNA before being able to interact with the network, and "accidental" cross pollenation is more or less impossible.

# Kademlia Awesomeness
* Distance function - XOR
  * 2.1 XOR metric 
Each Kademlia node has a 160bit node ID. Node IDs are currently just random 160bit identifiers, though they could equally well be constructed as in Chord. Every message a node transmits includes its node ID, permitting the recipient to record the sender's existence if necessary. Keys, to, are 160bit identifiers To assign (key,value) pairs to particular nodes, Kademlia relies on a node of distance between two identMers Given two IfiEbit identifiers, x and y, Kademtia defines the distance between them as their bitwise exclusive or (XOR) interpreted as an integer, d(x, = x y We first note that XOR is a valid, albeit non-Euclidean metric. It is obvious that that d(x, = 0, d(x,y) > 0 if x # V. and Vs,y d(s, y) = My, x) XOR also offers the triangle property: d(s, y)-Fd(y,r) > d(s,z). The triangle property follows from the fact that d(m, y)(D d(y,z)= d(s, z) and Va 0, b> 0: a + > a + b We next note that XOR captures the notion of distance implicit in our binary-tree-based sketch of the system. Ina fully-populated binary tr. of 160 bit ID, the magnitude of the distance between two IDs is the height of the smallest subtree caltaining them both. When a tree is not fully populated, the closest I.f tom ID x is the If whose ID shares the longest common prefix of x If there are empty branch® in the tree, there might be more than one leaf with the long.t comm. prefix In that case, the closest leaf to x will M the closet leaf to ID i produced by flipping the bits in x correspcmding to the empty branch® of the tree. Like Chord's clockwise circle metric, XOR is unidirectional.. For any given point x and distanced > 0, there is exactly one point y such that d(x,y)= Unidirectionality ensur. that all lookups for the same key ccmverge along the same path, regardl.s of the originating node. Thus, caching (key,value) pairs alum the lookup path alleviates h. spots. Like Poetry and unlike Chord, the XOR topology is also symmetric (d(x,y)= d(y,x) for all x and y) 
* K-Buckets routing tables
  * node, it updates the appropriate k-bucket for the sender's node ID. If the sending node already exists in the recipient's k-bucket, the recipient moves it to the tail of the list. If the node is not already in the appropriate k-bucket and the bucket has fewer than k entries, then the recipient just inserts the new sender at the tail of the list. If the appropriate k-bucket is full, however, then the recipient pings the k-bucket's least-recently seen node to decide what to do. If the least-recently seen node fails to respond, it is evicted from the k-bucket and the new sender inserted at the tail. Otherwise, if the least-recently seen node responds, it is moved to the tail of the list, and the new sender's contact is discarded. k-buckets effectively implement a least-recently seen eviction policy, except that live nodes are never removed from the list. This preference for old contacts is driven by our analysis of Gnutella trace data collected by Saroiu et. al. [4]. Figure 3 shows the percentage of Gnutella nodes that stay online another hour as a function of current uptime. The longer a node has been up, the more likely it is to remain up another hour. By keeping the oldest live contacts around, k-buckets maximize the probability that the nodes they contain will remain online. A second benefit of k-buckets is that they provide resistance to certain DoS attacks. One cannot flush nodes' routing state by flooding the system with new nodes. Kademlia nodes will only insert the new nodes in the k-buckets when old nodes leave the system.

**Comment by artbrock** [comment]
FWIW... I believe IPFS / LibP2P has implemented S/Kademlia (Secure Kademlia) which has a few change-ups from Kademlia.  See http://www.tm.uka.de/doc/SKademlia_2007.pdf for example.

I think there are a few other whitepapers which have contributed to greater security than kademlia originally had.

**Comment by christopherreay** [comment]
Routing Network Kademlia Oldest PING eviction anti DDOS
vs
Sort k-buckets by nearness rather than age, keep lastContact
  - When someone chats with you thats nearer - vetThem():
    - Whatever membrane criteria you have for the network
      - do they have an invitation
      - have they validated their indentity somehow (DPKI) (Hook)
      - Sybill resistance not just age but validation
  -

**Comment by christopherreay** [comment]
More documentation

https://docs.google.com/document/d/1OMSLPKEiEHRl4BS7t3yJUzTcjClIyzP628q8yDXGujM/edit

**Comment by christopherreay** [comment]
here is the test and the output for it for the first, basic, Get / Put Test in the existing libp2p-kad-dht test suite

```go
func TestValueGetSet(t *testing.T) {
	// t.Skip("skipping test to debug another")


	// Creates a DHT with two nodes and checks that a put can be read with a get
	//  The DHT nodes are referenced by variable pointers
	Convey("Test value get and set", t, 
		func () { 
			ctx, cancel := context.WithCancel(context.Background())

			fmt.Println("Test value get and set between two nodes")

			defer cancel()

			dhtA := setupDHT(ctx, t, false)
			dhtB := setupDHT(ctx, t, false)

			defer dhtA.Close()
			defer dhtB.Close()
			defer dhtA.host.Close()
			defer dhtB.host.Close()


			// Looks to me like this is done by setupDHT anyway
			// 
			// vf := &record.ValidChecker{
			// 	Func: func(string, []byte) error { return nil },
			// 	Sign: false,
			// }
			// nulsel := func(_ string, bs [][]byte) (int, error) { return 0, nil }

			// // Validator function always returns nil (success)
			// dhtA.Validator["v"] = vf
			// dhtB.Validator["v"] = vf
			// // nulsel always returns 0 (first / dumb selector)
			// dhtA.Selector["v"]  = nulsel
			// dhtB.Selector["v"]  = nulsel


			connect(t, ctx, dhtA, dhtB)

			log.Error("adding value on: ", dhtA.self)
			ctxT, cancel := context.WithTimeout(ctx, time.Second)
			defer cancel()
			err := dhtA.PutValue(ctxT, "/v/hello", []byte("world"))
			So(err, ShouldBeNil)

			ctxT, _ = context.WithTimeout(ctx, time.Second*2)
			val, err := dhtA.GetValue(ctxT, "/v/hello")
			So(err, ShouldBeNil)
			So(string(val), ShouldEqual, "world")

			log.Error("requesting value on dht: ", dhtB.self)
			ctxT, cancel = context.WithTimeout(ctx, time.Second*2)
			defer cancel()
			valb, err := dhtB.GetValue(ctxT, "/v/hello")
			So(err, ShouldBeNil)
			So(string(valb), ShouldEqual, "world")
		})
}
```
which outputs this:
https://visual.tools/static/pastebin/TestValueGetAndSet.log.html

**Comment by christopherreay** [comment]
Ive messaged whyareyousleeping since this: https://visual.tools/static/pastebin/TestNoTests.html seems to be a side effect of importing the DHT library.

I guess Ill wrestle golang to let me explore which import is causing the side effect for a couple of hours.

**Comment by christopherreay** [comment]
OK. Ive broken a good steps of the golang learning curve and am starting to produce good documentation on the tests.

**Comment by christopherreay** [comment]
```golang
func TestProvides(t *testing.T) {
	// example output: https://visual.tools/static/pastebin/TestProvides.html
	// t.Skip("skipping test to debug another")
	fmt.Println("dht_test.go: TestProvides")



	ctx := context.Background()

	_, _, dhts := setupDHTS(ctx, 4, t)
	defer func() {
		for i := 0; i < 4; i++ {
			dhts[i].Close()
			defer dhts[i].host.Close()
		}
	}()

	// connect the nodes, puts all nodes in all nodes routing tables
	connect(t, ctx, dhts[0], dhts[1])
	connect(t, ctx, dhts[1], dhts[2])
	connect(t, ctx, dhts[1], dhts[3])

	// Value provider layer of indirection.
	// This is what DSHTs (Coral and MainlineDHT) do to store large values in a DHT.
	//   so the Value is not placed "where it should be" in the DHT, but references to it
	// 			are stored in the "closestPeers"

	// dht[3] is the provider for all the keys in testCaseCids
	// 	 dht[3] uses findClosestPeers
	//   and sends a dht.sendMessage of a dht.makeProvRecord to all the closest Peers
	//     (which must be all of them
	//   to each of them
	//     as hosts of the key
	//   Done in parrallel
	for _, k := range testCaseCids {
		log.Debugf("\n\nannouncing provider for %s", k)
		// Provide is found in ./routing.go
		if err := dhts[3].Provide(ctx, k, true); err != nil {
			t.Fatal(err)
		}
	}

	// what is this timeout for? was 60ms before.
	time.Sleep(time.Millisecond * 6)

	// round robins all the nodes on the DHT
	//   looking for a provider for the testCaseCid
	n := 0
	for _, c := range testCaseCids {
		n = (n + 1) % 3

		log.Debugf("\n\ngetting providers for %s from %d", c, n)
		ctxT, cancel := context.WithTimeout(ctx, time.Second)
		defer cancel()
		
		provchan := dhts[n].FindProvidersAsync(ctxT, c, 1)

		select {
		case prov := <-provchan:
			if prov.ID == "" {
				t.Fatal("Got back nil provider")
			}
			if prov.ID != dhts[3].self {
				t.Fatal("Got back wrong provider")
			}
			if prov.ID == dhts[3].self {
				fmt.Printf("dht_test.go: TestProvides: foundProvider: %v\n", dhts[3].self)
			}
		case <-ctxT.Done():
			t.Fatal("Did not get a provider back.")
		}
	}
}
```

output: https://visual.tools/static/pastebin/TestProvides.html

**Comment by matthewjosef** [comment]
Dayzee,
Regarding:
// what is this timeout for? was 60ms before.
	time.Sleep(time.Millisecond * 6)

If my memory is correct, that delay was getting used as a hack to ensure that the tests would run in a proper sequence during a multi node test. By delaying that much on subsequent tests, we were able to avoid failures that occurred due to tests being run out of sequence. 

My nearly total illiteracy regarding code could mean I'm way off, but that is my memory.

**Comment by christopherreay** [comment]
significant memory since it wasn't us that coded it

**Comment by christopherreay** [comment]
##Boostrapping the routing tables
(all messages carry routing information, and all nodes operate as bootstrap communicators. I think that our "bootstrap" server would literally just have to be a node. We can also turn on "relay" for that node, which will ensure network completeness (All NATs and Firewalls traversable)

```golang
func TestBootstrap(t *testing.T) {
	// Create a DHT with 30 nodes and run bootstrap a few times to populate the routing tables
	//   
	// example output: https://visual.tools/static/pastebin/TestBootstrap.html


	// t.Skip("skipping test to debug another")
	fmt.Println("dht_test.go: TestBootstrap")


	// if testing.Short() {
	// 	t.SkipNow()
	// }

	ctx := context.Background()


	nDHTs := 30
	_, _, dhts := setupDHTS(ctx, nDHTs, t)
	defer func() {
		for i := 0; i < nDHTs; i++ {
			dhts[i].Close()
			defer dhts[i].host.Close()
		}
	}()

	fmt.Printf("\n\ndht_test.go: TestBootstrap: connecting %d dhts in a ring\n", nDHTs)
	for i := 0; i < nDHTs; i++ {
		connect(t, ctx, dhts[i], dhts[(i+1)%len(dhts)])
	}

	fmt.Printf("\n\ndht_test.go: TestBootstrap: boostrapping dht")

	<-time.After(100 * time.Millisecond)
	// bootstrap a few times until we get good tables.
	stop := make(chan struct{})
	go func() {
		for {
			log.Debugf("bootstrapping routingTables %d", nDHTs)
			ctxT, cancel := context.WithTimeout(ctx, 5*time.Second)
			defer cancel()
			fmt.Printf("\n\ndht_test.go: TestBootstrap:   ##call to bootstrap")
			bootstrap(t, ctxT, dhts)

			select {
			case <-time.After(50 * time.Millisecond):
				continue // being explicit
			case <-stop:
				return
			}
		}
	}()

	waitForWellFormedTables(t, dhts, 7, 10, 20*time.Second)
	close(stop)

	fmt.Printf("\n\ndht_test.go: TestBootstrap: bootstrapping complete (tables well formed)")

	if true {
		// the routing tables should be full now. let's inspect them.
		printRoutingTables(dhts)
	}
}
```

output:

**Comment by christopherreay** [comment]
Note from whyareyousleeping:
> <whyrusleepi> | dayzee: reading through it all now :)
[23:28] <whyrusleepi> | dayzee: worth noting that we havent finished the 'relay' code yet
[23:29] <@whyrusleepi>| it generally works, but i think there was some refactoring of the protocol in progress
[23:30] <      dayzee> | whyrusleeping: ok, thank you I will note that. We are sprinting for August 18th, and we wont actually need the relay to work for 
          our hackathon, but We will need it to work for the alpha release, so we'll work on it if needs be
[23:30] <@whyrusleepi>| sounds good
[23:31] <@whyrusleepi>| its a pretty big part of the libp2p improvement work we're going to be pushing quite soon, so its likely we get to it around the 
          same time as you
[23:31] <@whyrusleepi>| though help is always appreciated

**Comment by christopherreay** [comment]
Coral Sloppy Buckets and Geographic Cluster Levels

https://books.google.com/books?id=FkFsCQAAQBAJ&pg=PA48&lpg=PA48&dq=coral+cluster+level&source=bl&ots=kTFDCutlCv&sig=s3f5cfRdwrGDLPPN_L-22-9mywc&hl=en&sa=X&ved=0ahUKEwjMrrOlrYLVAhVM6WMKHXrICw0Q6AEIMTAC#v=onepage&q=coral%20cluster%20level&f=false

**Comment by christopherreay** [comment]
@artbrock I guess there are two core questions:

1. How does the "sloppy" in DSHT, with its automatic caching and keyload balancing properties  (check out JB's whitepaper about this) compare with the idea of gossiping neighbourhoods?
  * So what we are trying to do is create a complete DHT sharded effectively accross the nodes that are online NOW. This is not an "eventual find" setup.
  * there must be sufficient robustness in the neighbourhoods, such that no matter how many nodes "blink out of existence" at once, the DHT is able to redistribute itself amongst the remaining nodes without any data becoming inaccessible.
  * to me this problem presents nicely as a stimulus / response issue, rather than a static design issue.
  * from a stimulus response perspective
    * any given node has a set of data which "belongs to itself"
    * It maintains *at all times* that 40 (for example) of its closest neighbours have a complete copy of all of that data
    * it maintains a fairly active heartbeat with all those nodes.
    * If at some point the node becomes aware of another node which is %40 closer to it
      * do we announce to node 40 that we no longer require it as a neighbourhood partner?
        * WHEN? when we have completey loaded the newNode with our messages?
        * Do we wait for that node to completely validate all the messages (which could be a Lot) before telling node 40 that we no longer require its help?
        * Could we store the value on the DHT of the newNode, but mark it as "unvalidated, based on  validation of MyNodeID", such that some other Node looking for that value, would trigger a validation process before it could receive the value?
        * should the validation process go on slowly in the background (basically we cant have a node join the network and be told to analyse and validate its whole DHT neighbourhood responsiblity immiedately, as that would crush the device (phone) plus loads of other terrible things.
        * I think what to remember here is that the DHT is a useful device, but its the validation from the source chain that gives holochain its power, and that can be done JustInTime
    * **HOW do we determine "What" data "belongs to a node"** ?
      * It makes sense then that other nodes would treat entries on the DHT differently depending on whether they were "their" data or not
      * If data is "not mine" I keep it, but I do not ask other nodes to share it.
      * Overlap between what nodes consider "their data" is fine, as long as we avoid replecating "all the data" amonst all the nodes.
      * A node determines what data is "mine" depending on the distance of that data from itself in 256 dimensional space, relative to the size of the space taken up by its 40 neerest neighbours.
    * If a PutRequest arrives and we are the closest node we know of to the hash of the PRDAta, do we immediately perform validation? How many nodes should perform validation? All of them? Can we put "unvalidated" data on the DHT? 

2. In the existing *implementation* of the dht in go-libpwp-dht-kad, each message type (PING, GetValue, PutValue, GetProvider, PutProvider) is specified in "handlers.go" file, which acts as a link between capnProto specifications and the behaviour of individual nodes. 
  * can we do a hard exploration of this to determine if it can be used to implement all our requirements.
  * it is **true** that if we **can** use that, there is a lot of network stability behaviour built into the underlying message implementation (that PING, etc, are built ON / are subType of)

**Comment by zippy** [comment]
https://hackmd.io/MwNgrCBmBMULRgMYBMCGcAsAjLAGOqwYA7JmFiAKYgCMGNiwlQA=

**Comment by artbrock** [comment]
Holochain Requirements (that may different from Kademlia)
---
 - Different DHTs for each holochain
 - Peer addresses as hash of public key
 - Neighborhoods w/ Peer gossip
     - filter out old/processed messages
     - configurable neighborhood size
     - (probably) manage a peer list sorted by nearness of k size
     - You store any content that is as "near" as your farthest peer that list (peer stays in your list for X hours unresponded)
     - Track last gossiped message ID
     - Track number of gossip requests made to a peer, and number of succesful responses (Peer uptime = successes/requests potentially in a rolling time window) Detect if MY network connection is down vs. individual others down.
 - Validation before publish
     - Entry types
     - Able send only hash (not full data/chain with put)
     - Request validation package (potentiall full sourcechain)
 - MetaData we need support for
     - entry type (system specified, app specified),
     - signature of source and validators, 
     - links, 
     - attaches source, or multiple sources,
     - linked header entries on source chain?
 - Specialized Peer lists
     - Able to blacklist peers
         - for expired/revoked keys
         - for reported corrupt by neighbors 
     - Able to whitelist/approve peers for membrane mgt 
 - Peer Routing Overlay (Kademlia btree k-buckets)
 - Coral / CDN / Performance caching? (DSHT) S=Sloppy

**Comment by christopherreay** [comment]
Hi. Does hackmd send notifications of updates to participants? I updated it anyway https://hackmd.io/MwNgrCBmBMULRgMYBMCGcAsAjLAGOqwYA7JmFiAKYgCMGNiwlQA=?both

**Comment by christopherreay** [comment]
have a look at this: https://visual.tools/static/pastebin/TestPeriodicBootstrap.html#outputtingRoutingTablesBEFOREBootstrap its interesting. To see the original routing table (which is just a circle of DHT Nodes 0-1-2-...-29-0 ) with two entries in each, and then watch the bootstrap run. @zippy Does it make sense for me to ask you to create a branch putting some comments around the signal usage in dht_test.go/TestPeriodicBootstrap (through to dht_bootstrap.go/BoostrapOnSignal), or should we have a quick ten minutes talking about it, and I will write the docs whilst you are sheparding

**Comment by zippy** [comment]
@christopherreay Let's do it together like pair-coding...  Sounds more fun and it'll also help me absorb what you've been learning.

**Comment by christopherreay** [comment]
ok. shall we bother setting up a widget for collaborative editing on the bootstrap server (btw I don't know if you noticed, but yous guys took over ownership of the digital ocean machine I set up in March)

**Comment by zippy** [comment]
For pair coding Ive never done simultaneous editing, just switched off who's watching and who's typing, which seems to work fine. But I should get access to that be box...

**Comment by zippy** [comment]
I will do a code sprint to give it a shot (deliver by tue)

**Comment by zippy** [comment]
wip pushed to https://github.com/metacurrency/holochain/tree/263-kademlia
