### ISSUE TITLE
Structure holochain directories for Symbiosis with Mixin Zomes

### ISSUE THREAD

**Issue by christopherreay** [metacurrency/holochain#267]
## Mixins Repo
https://github.com/Holochain/mixins

## Goals
* Inidividual Mixin Directories should be blended into the full App DNA JustInTime on genesis [[is genesis the right term here?]]
* tests should run both standalone and as part of the whole organism
* Need to have UI functions that interface with the Zome
  * Would be nice to have UI widget components that are composable with a UI
* Schema properties may include references to other DNA hash which the Zome implies a bridge to
  * e.g. `holodex` indexing Mixin references the DNA of the indexing holochain
  * so the Schema entries should be mixed into the DNA to on genesis

## hc-scaffold
@neonphog - got any feedback?
* should pull the master of the Mixins repo and use it to supply the user with mixin options
* would be great if there was a configuration file in the Mixin that hc-scaffold could use to create interface tools for the Mixin
  * One or Many
  * Configuration

**Comment by christopherreay** [comment]
@zippy @lucksus @neonphog Design feedbacks would be good

* Currently thinking of putting a gene.json file into the zome directory, which can be mixed into the list of dictionaries in "Zomes": in the dna.json
* Umm... not sure how to (re)structure the directories best for this, if, indeed, any changes are indicated at all
* Various options might appear for "Mixin" specific configuratio files to help guide whatever automated systems are involved in the process

**Comment by zippy** [comment]
mixin symbiosis design moved to: https://hackmd.io/EYTgTAZiAsHQtGADAUwvaAOJn7AOxIDM8AJnKUjAMbTUCsKQA=== 
and will open tickets for specific parts of the work.
