### ISSUE TITLE
Command in README is wrong (go get ...)

### ISSUE THREAD

**Issue by GerryG** [metacurrency/holochain#27]
The command source was moved to a subdirectory, but the documentation was not updated. A little confusing to people checking this out.

**Comment by zippy** [comment]
Thanks fixed!

**Comment by GerryG** [comment]
Hey, thx. I'm digging in a little and like what I see. Please help me find the most current docs. I'd like to help by working on docs and diagrams as I get familiar.

I've been writing some random thoughts at http://gerry.wagn.org/

Be well.
