### ISSUE TITLE
bin2hc*commands

### ISSUE THREAD

**Issue by christopherreay** [metacurrency/holochain#279]
- [x] move checkInstalled and findAppDir to hccommon 
- [ ] switch multinode test to hcdev test
- [x]  machineReadable name

**Comment by zippy** [comment]
FYI what I did that's like `checkInstalled` is implemented in cmd/common.go `IsAppDir()`  and is used in Before() of hcdev

**Comment by christopherreay** [comment]
- [ ] implementing hccore as in [spec](https://docs.google.com/document/d/1IaW4G8IiKDBF6XdvhzmyjBzknaUam4Q_TGsawVv2PQo/edit#)
- [ ] creating a working test for MultiNodeTesting
- [ ] making scripts hardcode refer to $GOPATH/..../bin so no installation necessary

**Comment by christopherreay** [comment]
Dear @zippy  please could we implement a directory copy function into the common.go, its not as simple as you might thing

**Comment by zippy** [comment]
look at CopyDIr and CopyFile in utils.go

**Comment by christopherreay** [comment]
did you fix the bugs?

**Comment by christopherreay** [comment]
thanks xx

**Comment by zippy** [comment]
which bugs?  I haven't seen any tickets on bugs re those two commands.  Did I miss something?

**Comment by christopherreay** [comment]
Hey... oh the original code that it was made from had a couple of bugs in it. Ill have a look tomorrow. Im tired. Managed a ******** commit :)

**Comment by zippy** [comment]
Hey @christopherreay , if this is actually a ticket that's in progress by you, how about claiming it and moving it to in-progress? :-)

**Comment by christopherreay** [comment]
issue with moving multinode testing to `hcdev test` from `hc test` . Look at what is causing hc clone to fail

**Comment by christopherreay** [comment]
@zippy so ive added the change to move `hc test` to `hcdev test` into the docker template stuff.

The current error is that "the directory test/scenario/SCENARIO_NAME" doesnt not exist. Previously there was no directory "scenario" as the container for all the scenario tests. is this a deliberate design decision?

**Comment by zippy** [comment]
no I haven't added an explicit "scenario" directory, all sub directories are supposed to be scenario names, sound just like a mistake someplace...

**Comment by christopherreay** [comment]
Oh I put this comment in the wrong issue. lets do it again into

**Comment by christopherreay** [comment]
design for go version of multinode test
`hcdev scenario SCENARIO_NAME`
* for each role= .json file in scenarioDirectory
  * set a bunch of environment variables
    * HOLOCHAINCONFIG_PORT = FindSomeAvailablePort
    * HOLOCHAINCONFIG_ENABLEMDNS  = "true" or HOLOCHAINCONFIG_BOOTSTRAP = "ip[localhost]:port[3142]
    * HOLOCHAINCONFIG_LOGPREFIX = role
      * perhaps we should add another prefix control such that each role is identified as a color
          - [ ] [ ] [ ] two colors? one for the role word and the other for the output type?
          - [ ] [ ] [ ] just one color for all output types for each role
  * `hcdev --execpath /tmp/uuid/role  --debug test scenario role

**Comment by christopherreay** [comment]
xx
