### ISSUE TITLE
add key revocation function

### ISSUE THREAD

**Issue by zippy** [metacurrency/holochain#281]
Applications (and hcadmin) should be able to revoke the current private key used for checking all communications.

- [x] add new key/agent entry to chain
- [x] key/agent entry to include json identity blob for revocation method + more
- [x] update networking, i.e. close down old node and open up new node.
- [x]  add revoked node id to gossip blacklist (#226)
- [x] add otto implementation of updateAgent()
- [x] add zygo implementation of updateAgent()

**Comment by zippy** [comment]
Need to fix the fact that after running updateAgent, the App.Key.Hash is not longer correct!
Also, I think this means we also need to have two things: App.AgentPerm.Hash, and App.AgentCurrent.Hash to distinguish between the two.

**Comment by zippy** [comment]
I will add App.AgentTop.Hash and leave the permanent agent as App.Agent.Hash.

**Comment by zippy** [comment]
Also updating App.Agent.String!

**Comment by jackThammer** [comment]
With the latest update the updateAgent({Identity;""}) the App.Key.Hash doesnt update. only the top of the agent updates. is their a particular reason for that?
Cause in the previous version the App.Key.Hash changed and the App.Agent.Hash stayed the same.
I thought in the Identity case the App.Agent.Hash & App.Agent.TopHash would stay the same just the App.Key.Hash would change.
