### ISSUE TITLE
hcdev clone shouldn't add db & config

### ISSUE THREAD

**Issue by zippy** [metacurrency/holochain#303]
service.Clone() function creates a db and config file for running.  We need to add an option for use by hcdev --clone where it just copies the code and doesn't set things up for serving.

**Comment by christopherreay** [comment]
does that still require a new uuid. Yes - there i salready a flag to the clone function to do that
Add a new flag for the db copy stuff, becasue we dont wnat ot run it

**Comment by zippy** [comment]
fixed in 46541e3789c3760
