### ISSUE TITLE
write Go only version of multinode test

### ISSUE THREAD

**Issue by christopherreay** [metacurrency/holochain#309]
#### psuedocode

`hcdev scenario SCENARIO_NAME`
* for each role= .json file in scenarioDirectory
  * set a bunch of environment variables
    - [ ] HOLOCHAINCONFIG_PORT = FindSomeAvailablePort
    - [ ] HOLOCHAINCONFIG_ENABLEMDNS  = "true" or HOLOCHAINCONFIG_BOOTSTRAP = "ip[localhost]:port[3142]
      - [ ] mdns
      - [ ] bootstrap
    - [ ]  HOLOCHAINCONFIG_LOGPREFIX = role
      * perhaps we should add another prefix control such that each role is identified as a color
          - [ ] two colors? one for the role word and the other for the output type?
          - [ ] just one color for all output types for each role
  - [ ] `hcdev --path pathToSource --execpath /tmp/uuid/role  --debug scenario role`

#### timing
* Can we just run all the holochains with `go ....` and use a channel to synchronise them?
* Else they will be within a few milliseconds anyway

#### justification blurb
* much much simpler (with new hc commands)
* we are not using the power of docker for anything
* will enable running multinode tests with different kinds of holochain nodes, again, much more easily

**Comment by christopherreay** [comment]
@zippy can you checkout this latest branch and review the output.. actually Ill post some example output here as well, and point out what I think is weird.

[testoutput.txt](https://github.com/metacurrency/holochain/files/1203617/testoutput.txt)

ive pasted the string ZIPPYZIPPY in four places in the output

**Comment by zippy** [comment]
see latest commit to 297-... for one fix, working on the other parts next...

**Comment by zippy** [comment]
03853d89a67452 fixes the hard crash in the output, which was because TestScenario() in apptest.go wasn't running the necessary Reset() & GenChain() before starting the test.  Now the tests run, but don't pass.  I'm not sure yet if that's a problem with the clutter tests/app, or if the networking isn't operational, but that's the next step to look at.

**Comment by christopherreay** [comment]
Change the name of "port" to "peerport", rather than the ui port.

**Comment by christopherreay** [comment]
OK. so commit 1e39dd8 just takes ages to run the tests. the two command line things are clearly being run one after the other

**Comment by christopherreay** [comment]
we are in the state https://github.com/metacurrency/holochain/tree/tmp_279_348_merge trying to determine why gossip is not working

**Comment by zippy** [comment]
My current guess is that gossip is working, and that the scenario tests in clutter and holochat are currently borked.  So next steps are:

- [ ] confirm scenario tests clutter
- [ ] confirm scenario tests holochat
- [ ] add canonical scenario test to GenDev as per #328

**Comment by zippy** [comment]
https://github.com/metacurrency/holochain/tree/tmp_279_348_343_merge shows holochat working after merge with 343!

**Comment by christopherreay** [comment]
@zippy  please check out this output, which is from the head of 279-dayzee

There are three points marked with ZIPPYZIPPY
https://visual.tools/static/pastebin/testPrefixColor.html

could you help me determine why the Logger struct, which appears to have its PrefixColor set by the SetPrefix function, then appears to have a blank PrefixColor, whilst the "Name:" parameter remains the same?
