### ISSUE TITLE
create docs for DNA api

### ISSUE THREAD

**Issue by zippy** [metacurrency/holochain#32]
use #31 as a reference for documenting what functions are available to DNA authors

**Comment by artbrock** [comment]
This has been changing. I'm going mark this complete after I document the current iteration of changes:
 - [ ] directory re-org
 - [ ] exposing functions via DNA file
 - [ ] link type schemas
 - [ ] shared=public/private/partial

**Comment by zippy** [comment]
Starter page here: https://github.com/metacurrency/holochain/wiki/DNA-Reference

**Comment by artbrock** [comment]
updated and reformatted it... it's coming together... needs a few more details.
