### ISSUE TITLE
As a team we need a tool to easily check if the examples run with the current version of Holochain

### ISSUE THREAD

**Issue by zippy** [metacurrency/holochain#329]
Need to write a script/program which runs through all the examples in the holochain repo and tests them against current version holochain/master. @christopherreay wanna do this? I'm ok that it's not automatic, or part of travis for now, but we should just have it...

**Comment by lucksus** [comment]
would be much easier for the script to tell if the tests failed if the HC test suite would print errors to the standard error output

**Comment by lucksus** [comment]
Maybe the new feature ```hcdev init --cloneExample <example>``` could help?

**Comment by zippy** [comment]
re std error, this is very easy to do because the logger allows you to set a particular stream for each log type, and the failed test go to their own logger.  I have added a ticket #360 for this part
