### ISSUE TITLE
putLink over existing link not implemented

### ISSUE THREAD

**Issue by zippy** [metacurrency/holochain#348]
We get this as a panic error in clutter when attempting to update the handle to the same thing (and probably other places) and it causes a hard crash, so to reach  our weeks goal of App integration I'm going to add this as bug.

**Comment by christopherreay** [comment]
whats the best way to review this?

**Comment by zippy** [comment]
Not too sure about "best."  At the low end of the spectrum review is just being aware of the changes we are all making, so noticing is enough, in the middle is catching typos, mis-spellings in comments, and code inefficiencies. At the high end of the spectrum would be deep understanding of the consequences of the changes, and catching unseen problems or mistakes, this would be akin to approval.  All seem fine to me depending on the context.  Maybe we could come up with a pattern to self-identify what type of review we are giving when we click accept/approve?
