### ISSUE TITLE
as a chain user my private entries should stay private

### ISSUE THREAD

**Issue by zippy** [metacurrency/holochain#352]
- [ ] make sure that when chain gets shared in verification package, that only the headers of private entries are included (not the body)

**Comment by lucksus** [comment]
after starring at func (*Chain) MarshalChain() now for too long, I would like to refactor (almost rewrite it). I don't really understand the no headers option. In what context does it make sense to not get headers? I would assume (and like to reduce the complexity) by always writing out all headers and then omit only entries if they are private or if a list of entry types is given.. makes sense?
