### ISSUE TITLE
as a user bridging apps I want to specify app specific data at bridge time

### ISSUE THREAD

**Issue by zippy** [metacurrency/holochain#354]
Currently the low level code allows you to pass appData into bridgeGenesis, but hcdev has no way of getting this data from the user and passes in an empty string.  This should be fixed!

**Comment by christopherreay** [comment]
as an "agent"? please make more clear

**Comment by zippy** [comment]
53602aa9bd adds this for hcdev.  The reset of this ticket is more for how the "end-user" would pass that data in, i.e. via hcadmin, or via hpm.

**Comment by zippy** [comment]
this got done a while back.
