### ISSUE TITLE
as a developer, I want a function that can tell me if my app has been bridged

### ISSUE THREAD

**Issue by zippy** [metacurrency/holochain#355]
- [ ] bridges() returns a list of objects [{Name:x,Hash:y,Side:from/to},...]

**Comment by christopherreay** [comment]
is it possible to bridge an appwithout changing the dna?

**Comment by zippy** [comment]
On the "Caller" side it's only possible to bridge without changing the DNA, i.e. it has to know the DNA of the app it's bridging to and most likely will be bridging by having mixed in a zome that the bridgeTo (callee) app developed.  On the "Callee" side as many different apps as have mixed in the client zome (or made their own) can bridge to it.
