### ISSUE TITLE
as a core dev I want one debugging interface that also reveals current file in the debug output

### ISSUE THREAD

**Issue by zippy** [metacurrency/holochain#363]
Currently we have IfDebugging() {fmt.Printf} and Debugf()   unify to one patter, and make the Debugf() call also automatically (or if not possible) have filename parameter.

**Comment by christopherreay** [comment]
what about other behaviors that happen during the state of debugging. 

or potentially have an IsTesting() function?

there was an offline agreement to put mutableContext tracking into IsDebugging() blocks.

**Comment by christopherreay** [comment]
Hi. I appreciate what is being attempting with these ticket names, but.. I have never seen a ticket name like this in any other repo, and the ticket title contains absolutely no information at all. can we please rain back on .. whatever this it

**Comment by zippy** [comment]
- [ ] I would like to be able to turn on & off the mutableContext output because its so noisy.

I did add something to deal with is Testing in one case see: https://github.com/metacurrency/holochain/commit/e0a92a79236fea3d54fb496c8d163d184c423b72

**Comment by christopherreay** [comment]
Aye. I think so

**Comment by zippy** [comment]
One thing to note here is that Debugf is available via holochain.  And we may want to separate the debug info that comes from holochain package than what comes from the commands themselves.

**Comment by zippy** [comment]
Another thing here is to distinguish between turning on debugging for the purposes of debugging an HC app, i.e. seeing things like gossip, output etc, and turning on debugging for core development.  Currently that's mixed together.
