### ISSUE TITLE
‘hcadmin init’ fails: Error: mkdir : no such file or directory

### ISSUE THREAD

**Issue by kseistrup** [metacurrency/holochain#392]
I just installed holochain as per the instructions. However, ‘hcadmin init’ fails without being helpful:

```sh
$ hcadmin init username@example.com
Error: mkdir : no such file or directory
$ hcadmin -V init username@example.com
hcadmin version 0.0.2 (holochain 15) 
Error: mkdir : no such file or directory
$ hcadmin --debug init username@example.com
Error: mkdir : no such file or directory
$ mkdir ~/.holochain
$ hcadmin init username@example.com
Error: mkdir : no such file or directory
$ go version
go version go1.8.3 linux/amd64
$ uname -osr
Linux 4.12.8-2-ARCH GNU/Linux
```

**Comment by christopherreay** [comment]
Thank you. I can confirm this happens on my system as well.
I am looking into it now. Likelyhood it will be fixed when PST comes online

**Comment by christopherreay** [comment]
@kseistrup this is fixed, and merged to master

**Comment by christopherreay** [comment]
The issue was that the cmd.GetService is returning sometimes the ErrServiceUninitialised, which means that the wide scope `root` string was never set at all, even if -path was set or whatever. I created a new function to explicitly set root, whilst respecting that this situation cannot arise in hcd

**Comment by kseistrup** [comment]
I can confirm that initialization does indeed work now. Thanks for your swift action.
