### ISSUE TITLE
fix Sys entry type data formats

### ISSUE THREAD

**Issue by zippy** [metacurrency/holochain#402]
currently the DNA, Key, and  Agent entry types are serialized to the chain differently from every other entry types which are either plain strings, or JSON depending on the entry type definition.  This is bogus because it means that they are unreadable when loaded into the app via query().   So this needs to be fixed for:

- [x] DNA this doesn't get returned, should never be needed by anyone.
- [x] Agent
- [x] Key
- [x] Links

so that they are properly available to: 

- [x] query()
- [x] hcdev&hcdmin dump

**Comment by lucksus** [comment]
Check if this fixes #232
