### ISSUE TITLE
Tests failing because of timestamp output change go1.8 -> go1.9

### ISSUE THREAD

**Issue by christopherreay** [metacurrency/holochain#405]
Update the tests to work for both version of go.

example output: https://visual.tools/static/pastebin/389.dayzee.test.output.html
search for "Failures:" in the output to find issues.

**Comment by christopherreay** [comment]
Output from the current master:
https://visual.tools/static/pastebin/405.1.test.html

There are 4 errors:
* three of the errors are cuased by timestamp output. 
* one of the errrors is caused by colour output vs non colour output

**Comment by christopherreay** [comment]
Error 1:
The LHS of the SO test is a
* Message struct from node.go
the RHS of the SO test has 
* gone through ByteEncode and been put in buntDB

**Comment by christopherreay** [comment]
Ok, so @zippy check out
https://visual.tools/static/pastebin/405.2.test.html

Search for 
10:30:06.156003284

Ill push the branch which has the printed outputs in it to
405-fixTests1.8-1.9

**Comment by zippy** [comment]
The issue is that 1.9 adds monotonic time.  see: https://golang.org/doc/go1.9 and search for monotonic.  It looks like it does so in a transparent way such that if monotonic time reading is available the %v will also include that in the string text.   If you check out https://golang.org/pkg/time/#hdr-Monotonic_Clocks  you'll see that there are conditions that strip the monotonic data, which is I guess what's happening once the data gets serialized and unserialized.  

Thus for our purposes, I think all we have to do is manually strip the monotoic data in the tests so that the read correctly, so I think:

```
m1.Time = m1.Time.Round(0)
m2.Time = m2.Time.Round(0)
```

at line 188 of gossip_test.go would do the trick.

**Comment by christopherreay** [comment]
So Im not comfortable with changing the tests such that non matching data passes the test (Im not sure if you are pulling my leg! )

From my perspective there are two options:
1. Change the serialize / deserialize behaviour so that the data stored includes all the data created
  * I got as far as this as Im really able to without understanding why the code I wrote creates a "nil" results, when it looks like to me I have trivially just unserialized the data just after its be serialized. If you could give me a hand with that, perhaps we can address that.
2. Change the pieces of code that generate the timestamps to use Round(0)
  * I have already done this to `node.go/NewMessage` and happily those two failing tests pass :)
  * Ill commit that when Ive written this message.
  * and Ill find the other code with a timestamp (which is failing line 155 validate.go)

Oh, is there anyone running go1.8 still? 
 - [ ] Shall I set up a test space for go1.8? 
 - [ ] I suppose I should. We could also include tests for both versions in the Makefile

**Comment by christopherreay** [comment]
Are you trying to say that *interally* these timestamps are *always* serialized? So the question doesnt arise?

**Comment by christopherreay** [comment]
OK. So I looked at this. It is non-trivial to remove the timestamps from the test output.
Ive added time.round(0) to the NewMessage function in node.go, which fixes the tests for gossip_test.go and node_test.go, 
outputting: https://visual.tools/static/pastebin/405.3.test.html

leaving the test for validate_test.go failing, which outputs this:
https://visual.tools/static/pastebin/405.3.diff.validate.go.html

@zippy the three solutions still seem to remain to me:
1. would be to use regex to remove the +m=#######.## from the test output
2. hunt down the places that timestamps are added into this stuff, and add .round(0) to them
3. find out how to get the data storage layer to keep the extra binary data

**Comment by christopherreay** [comment]
this removes on of the errors, leaving:
https://visual.tools/static/pastebin/405.4.diff.validate.go.html

**Comment by christopherreay** [comment]
Which appear to the the timestamps built into the DNA and the AGENT entries in the source chain.

The issue that I am seeing with this, is how are the actual APP tests going to work if this is an issue with them?

**Comment by christopherreay** [comment]
now there are zero errors in the read / write to source chain of the output
as in here: 
* https://visual.tools/static/pastebin/405.6.test.html
* search for: "it should be able to make a validate package"

**Comment by christopherreay** [comment]
Next stage is to remove the debugging output strings

**Comment by christopherreay** [comment]
https://visual.tools/static/pastebin/405.8.test.html

**Comment by christopherreay** [comment]
All tests pass on my local machine. Investigating Travis issues
