### ISSUE TITLE
Test/proof Holochain really works across many machines across the internet

### ISSUE THREAD

**Issue by lucksus** [metacurrency/holochain#444]
* minimal set of changes to app testing framework (leverage clone of app test)
* docker?
* preferably use clutter

**Comment by christopherreay** [comment]
exciting. if there's anything docker related yous want a quick chat about, give me a phone.

**Comment by zippy** [comment]
- [x] fix clutter to work with current master
- [ ] fix hcdev scenario to allow use of bootsrap server
- [ ] fix hcdev to allow setting clone start number. 
- [ ] expose clone number to test in testapp.go
- [ ] create a clutter scenario with large number of clones that takes into account other instances running at the same time and syncing over the net via the bootstrap server.
- [ ] write script that starts scenario on multiple servers using ssh or other RPC simultaneously.

**Comment by zippy** [comment]
8bd7e4b9 on https://github.com/metacurrency/holochain/commits/444-multiserver-scenario adds the changes to hcdev
