### ISSUE TITLE
expectations ugly when not met and include %

### ISSUE THREAD

**Issue by zippy** [metacurrency/holochain#461]
because our substitutions are like %h% and such, this collides with % in sprintf and produces ugly output when the expectation fails, eg: `Expected: %!s(MISSING)ever%!e(MISSING)ric@isotopy`

**Comment by christopherreay** [comment]
I tend to use bang bang for substitutions since it's programmatically low in meaning. !!h!!

is there a label on tickets that require changes in source?

**Comment by christopherreay** [comment]
I meant commits
