### ISSUE TITLE
finalize decisions about serialization of entry encoding

### ISSUE THREAD

**Issue by zippy** [metacurrency/holochain#47]
Complete abstraction of Entry for different entry encoding types:
- [ ] make use of Entry type actually work for different interface{} implementations instead of only working for GOB
- [ ] complete JSON
- [ ] add BSON
- [ ] add choice of encoding type to DNA defaults to BSON

**Comment by zippy** [comment]
Currently we are using Gob, and that's not good enough for production

**Comment by artbrock** [comment]
Note to selves... Look at flatbuffers for this. It has good go support and both binary and human friendly formats.

**Comment by artbrock** [comment]
We'll also probably need to expose whatever serialize/deserialize function we go with to the apps if we want to be able to do hash matching stuff with the hash() command.

**Comment by christopherreay** [comment]
I'd probably pick json with trailing blobs

**Comment by christopherreay** [comment]
I'd probably pick json with trailing blobs

**Comment by dukejones** [comment]
When we were looking at implementing a wire protocol for a point of sale system we were building out at a startup I was at a few years ago, there were a few open standard ones that support binary data, work well and are quite efficient.
[protocol buffers](https://developers.google.com/protocol-buffers/docs/overview) - Sort of the "strongly typed" choice of the wire protocol world. Very efficient, used internally at Google.
[BSON](http://bsonspec.org/) - It's just like JSON but without extraneous ASCII and supports BinData.
Thrift - Facebook's protocol... doesn't seem to have a golang implementation
People seem to be raving about [Cap'n Proto](https://capnproto.org/), written by one of the authors of protobuf v2.
There's always ASN.1, if you're a masochist.

This was 2013 when I last looked deeply at this, there may be others by now. 

I'd recommend Cap'n Proto, or perhaps BSON.

**Comment by dukejones** [comment]
Dang Cap'n Proto has a wireshark plugin, and a CLI utility for packing/unpacking, and great language support.

**Comment by GerryG** [comment]
I have a WIP branch where I am adding the plumbing for a WireType setting. https://github.com/GerryG/holochain/pull/3

It isn't ready yet, shouldn't be to long.

**Comment by dukejones** [comment]
My personal feeling is that being able to switch between wire protocols would be disastrous, sort of like having a choice of several communication similar but not equivalent to HTTP, and having to negotiate which protocol to use.  In a stateless protocol this is on every request.  I'd say define something that works well.  If there's something else that is far superior, use something analogous to SPDY: a protocol overlay to communicate the same data between participating clients, but minimum have a well-defined fundamental standard that sets the bar for network communication that everyone can participate in.

**Comment by GerryG** [comment]
I don't think a DNA would want to support more than one (normally, I can see exceptions, but app specific), but being able to choose one at the app architecture phase is a good thing.

**Comment by artbrock** [comment]
@dukejones After some more research, I'm on board with Cap'n Proto, I had already liked it, and like Kenton Varda and sandstorm too. But I think security points are what is selling me on it now.

Speaking of which, @GerryG , I'd need to understand why you think apps should be able to change the wire protocols. From my vantage point, that should be WAY below the reach of apps, and given peered gossip seems to invite security problems with malicious inputs, buffer overruns, flooding attacks. I'd prefer to focus on making one wire protocol more secure, than allow the apps to configure it. The whole point of the underlying Go libraries of holochain, is to let the apps stick to a focus of data structure and validation, with the underlying distribution being handled by holochain so they don't have to deal with that, and the UI at a separate layer of flexibility altogether.

**Comment by GerryG** [comment]
As we discussed, this is not a property of the dna or app, but of the DHT infrastructure. In other words, this would be a DHT configuration, not a holochain one. In principle, there is no reason nodes could not be connected to DHTs with different protocols, even for the same DNA/chains. The apps would not really "know" about it, it would just be part of the DHT setup.

In any case, having the code such that we could change the wire format by just changing a setting and providing the encode/decode interfaces that are needed. In the end, this is about not wanting the wire format to be too go centric.

This said, it is a backlog issue in any case.

**Comment by christopherreay** [comment]
just gonna agree with Arthur.

security primary focus
human readability... maybe a choice of the dna

I suppose actually the dnas child choose their wire protocol, since all
holochains are orthogonal, bridged on point. if there was some massively
good reason for adna to want it's own protocol, then no reason not to allow
it, but no reason to implement more than one in the "core"

**Comment by timotree3** [comment]
Down the line I think semantic trees would make sense.

**Comment by artbrock** [comment]
Eric and I discussed... we're gonna give Cap'n Proto a shot.

**Comment by christopherreay** [comment]
https://github.com/Blosc/bloscpack

**Comment by zippy** [comment]
decision completed, work now in #222
