### ISSUE TITLE
I can't follow anyone

### ISSUE THREAD

**Issue by frogbirdsnake** [metacurrency/holochain#548]
Maybe I'm on the wrong version of holochain/clutter. I've been downloading these since October (and as recently as today) and have been on clutter since then as "greg." When I get on localhost: 3141 I can't find anyone to follow, it's just me alone in the universe.

**Comment by philipbeadle** [comment]
Yep for now there arent enough using it at any one time.  So to fix that I made a docker-compose file that runs up 3 clutters and its own bootstrap so you can try it out.  Try it out here https://github.com/Holochain/clutter

**Comment by frogbirdsnake** [comment]
Hey Philip,

My experience was that even when Matt and I were side by side, both running
clutter, we still could not find one another. Perhaps we were using
different versions? Regardless, is it not possible to follow someone when
they're offline? I thought that was the work of the DHT?

Thanks for your consideration,

Greg
