### ISSUE TITLE
Implement Monotonic behavior on DHT

### ISSUE THREAD

**Issue by artbrock** [metacurrency/holochain#55]
- [x] del(hash) marks the hash as in the deleted set
- [x] delLink(hash, type, data) marks that meta data as deleted
- [x] query options to retrieve entries & links in non-live state (status mask)
- [x] mod(oldhash, newhash) should mark item as modified, and add Link data REPLACED-BY -->New Hash
Obviously, each of these actions need to be able to be validated against a source chain entry authorizing the action.

**Comment by zippy** [comment]
additional actions above now pending the completion of #141

**Comment by zippy** [comment]
Fix this to make sure there is a commit on the authoring chain that represents these actions.

**Comment by zippy** [comment]
Make getLink collect links through modified bases.
