### ISSUE TITLE
Dump Chain as JSON

### ISSUE THREAD

**Issue by philipbeadle** [metacurrency/holochain#561]
Add a new method to hcadmin dump --chain --json

To make it easier to visualise the chain growth.

**Comment by clarenceb** [comment]
I have a working implementation for this.  Still working on the tests.  Currently, `--json` flag can be used with `hcadmin dump --chain` but not yet for `hcadmin dump --dht`.

**Comment by philipbeadle** [comment]
Merged into develop.
