### ISSUE TITLE
Add web hooks into HC so we can sub to events from the app rather than polling

### ISSUE THREAD

**Issue by philipbeadle** [metacurrency/holochain#573]
rather than the UI polling the DNA every few seconds for updates it would be better to have web hooks that send events when the chain or dht get updated

**Comment by philipbeadle** [comment]
Also this would make it much simpler to build a visualiser for the chain, dht and gossip.

**Comment by zippy** [comment]
The ticket where we talked about this is #58

**Comment by jryanhaber** [comment]
totally agree

**Comment by philipbeadle** [comment]
Included in 58.
