### ISSUE TITLE
add expose level to FunctionDef to specify the domain where function is visible to all cross-zome calling

### ISSUE THREAD

**Issue by zippy** [metacurrency/holochain#64]
FunctionDef needs a "ExposedTo" enum type variable that sets whether the function is fully exposed (i.e. to the UI) or just to other Zomes.

Then we can implement adding access to cross zome function calling where within the every nucleus, there should be a "call" function that allows you to call both fully exposed, and cross-zome exposed functions from other zomes.

**Comment by GerryG** [comment]
Looking at the code state around dna, zomes and entry/function definitions, first I want to do some non-functional refactoring to improve organization and code clarity. To that end I want to examine any existing coding standards and establish a minimal process for evolving it. At some point we may even split holochain into several imports according to some code divisions, but for now I will keep them all as one package, one source directory (cmd subdirs excepted as technically already not in the library, but using it)

Please comment here as you have time and I will post when I've pushed code onto branches so you can take a look and offer guidance.

I will put in issues for the refactoring as I start it, etc.

**Comment by zippy** [comment]
So this raises a red-flag for me.  Obviously you can do as you like with all this, but I'm a strong advocate for not over-generalizing which means not refactoring too soon.  In the comment above I see you going right to re-architecting things, whereas this ticket is, I think, pretty straight forward, and can be implemented without that.  If you think that something needs refactoring, then that should go in a separate ticket, where it can be discussed and prioritized, but as you can see above, none of what you wrote is actually germane to the task requested by this ticket, it's about "coding standards," refactoring and code clarity.  All reasonable goals, but, not part of this ticket, nor, I think necessary to move the ball forward at this time.

**Comment by GerryG** [comment]
I'm actually trying to avoid this pitfall. I agree those need to be separate tickets. I've learned the hard way about the need to keep changes small and incremental. I agree that the refactoring doesn't have to come first, but I think working on some small refactorings can be useful.

This is also in support of my goal to be able to call a nucleus written in go from go and leave out all the language flipping in the nucleus. I am implementing this for me own reasons independent of any issues I take on the help out the overall project. If I can't do some refactoring tickets on the lead up to that, I think the process will break down.

I think that refactoring that puts code more or less where it belongs is best done early. You need to get code motion settled down or the merge conflicts get difficult to manage. I'm commenting because I don't want to mess anything up and make more work or double work, etc. I want the relational hierarchies to be better represented in the code organization and layout.

More generally, I find some of the coding practices hard to deal with, most egregious are all the one character identifiers. We need a place to air and debate this kind of things. I'm new to the project and I'm not trying to just throw my weight around, but I do have considerable experience with OS and commercial projects and teams. I want to contribute in leadership, not to create problems for you.

**Comment by GerryG** [comment]
What is the ticket that this change depends on?

**Comment by GerryG** [comment]
This comment may have been out of place. I don't want to refactor everything just for a small feature, but as I understand the architecture better, I suspect I would do all of this very differently.

When I started to work on Wagn, I did take on too big of a chunk at a time and Ethan didn't always totally get why I was doing a lot of the changes I was adding, but in the end we learned a lot from one another. He taught me a lot about agile process and working with a coding partner. The architecture we ended up with wasn't exactly what either of us set out to do, the the results are a really impressive architecture.

If you don't resist what I'm trying to do and instead support it as you can, then I think we will do much better.

If this ticket is just a detail of implementing your design for another ticket, please link it so we can discuss the design on the right tickets.

**Comment by GerryG** [comment]
I deleted the out of place comments and created an Epic issue that I will use as a refactoring guide and bite off bits of it. You input there is very much welcome. I want to do constructive refactoring.

**Comment by GerryG** [comment]
If I understand, this means an attribute added to function defs in the dna-zomes data?

**Comment by zippy** [comment]
yes the FunctionDef struct defined in nucleus.go

**Comment by GerryG** [comment]
And having it load from the zomes. Do you have a couple of values you want to set. You want enum constants and symbols internally, but in the zome we can have string values that can map to constants, or is that out of scope?

**Comment by zippy** [comment]
I think exactly so. Since these things are defined in text files, my approach was to just have string constants we use in the code.  eg the CallingType is one of :

// calling types
const (
	STRING_CALLING = "string"
	JSON_CALLING   = "json"
)
both defined in nucleus.go.  Something similar I think for the ExposedTo property

**Comment by GerryG** [comment]
Perfect, that's what I was thinking.

**Comment by GerryG** [comment]
You don't want to implement any functionality yet? Maybe require 'public' to Call or ?

**Comment by zippy** [comment]
Yes, I think the point is to actually make these functions available inside the zome.   For example, if you look at the chat example, there's a bunch of redundant code because you can't call across libraries.  

I see two ways forward:  one is to actually add the function into nucleus, so it's directly available.  This is nicest for app programmers, because then they can just call any exposed functions from other zomes.  But perhaps this adds too much overhead each time a nucleus gets built as for any time the VM gets spun up, its not likely to actually call that function.  Thus instead we should have a generic "call" function through which you can call such exposed functions, and it fails if you give it non-existent/non-exposed names.  Don't have a strong feeling about this one way or the other, and it seems about the same amount of work.

**Comment by GerryG** [comment]
Ok, so you want this to control that feature. Then you want it implemented as well, correct?

This may be your answer to my question about referring inter-zome. You want to just merge the public functions into all zome's function lists? We can't rely on prefix. or something in the nucleus, could use zome_name_fucntion_name when it could be ambiguous. The basic issue is how to handle inter-zome name collisions for types(entry defs) and functions

**Comment by GerryG** [comment]
So, this is the point at which I'd like to do some other refactoring before actually using this setting. What I want you to tell me is how you want it to work. We don't have to actually decide until a later point in the development of this branch. What you want is inter-zome calling, right? I find that to be part of a small complex of concerns, if you are not in a rush for part of it, I would beg patience until I have something to show you.

**Comment by GerryG** [comment]
See also #140 point 7. I think I should make a new ticket for that specifically, but they will be one merge by the time it is all ready.

**Comment by zippy** [comment]
Gerry, can you please rebase your expose_to branch against master, and then do a new pull request for it to the branch I just pushed up called exposedto-64 with the work you did?  That way I can finish this ticket without having to retype the work you did.

**Comment by GerryG** [comment]
Sure, I'll try to get to it tomorrow or soon after. Is that soon enough for you?
