### ISSUE TITLE
put variable data into it's own directory in .holochain

### ISSUE THREAD

**Issue by zippy** [metacurrency/holochain#66]
like "data" or "var"

**Comment by artbrock** [comment]
See ticket #67
Structure of subdirs of .holochain

chainname (dir)

chainname.conf
db (for the chain.db and the dht.db)
test (for the automated tests)
ui (for the pluggable UI files)
dna (all the stuff which gets hashed into the DNA entry of the chain)
dna.json (dna file which enumerates zomes, zome script files, entry schemas)
zomename1 (dir)
zomesname1.js (or whatever file extension for the script type)
schema1.json
schema2.json
zomename1 (dir)
zomesname2.js (or whatever file extension for the script type)
schema1.json
schema2.json

**Comment by zippy** [comment]
This is implemented except for one thing, that the config file is actually called: config.<ext> where <ext> can be yaml/toml/json depending on your format choice.
