### ISSUE TITLE
home each zome in a directory in the .holochain dir

### ISSUE THREAD

**Issue by zippy** [metacurrency/holochain#67]
Figure out if we should also have a "zomes" directory...

**Comment by aquabu** [comment]
Maybe something like

zomes [dir]
- zome1 [dir]
-- bin [dir]
--- main.js
-- schemas
--- schema1.json

**Comment by artbrock** [comment]
Yeah... upon discussion I think we're going to restructure the .holochain directory for each chain to be like:

chainname (dir)
 * chainname.conf
 * db (for the chain.db and the dht.db)
 * test (for the automated tests)
 * ui (for the pluggable UI files)
 * dna (all the stuff which gets hashed into the DNA entry of the chain)
    * dna.json (dna file which enumerates zomes, zome script files, entry schemas)
    * zomename1 (dir)
       * zomesname1.js (or whatever file extension for the script type)
       * schema1.json
       * schema2.json
    * zomename1 (dir)
       * zomesname2.js (or whatever file extension for the script type)
       * schema1.json
       * schema2.json
