### ISSUE TITLE
hc status reports no installed chains when hc serve is running

### ISSUE THREAD

**Issue by chrislarcombe** [metacurrency/holochain#70]
When server is running (eg., hc serve clutter) and I run **hc status** it says "no installed chains" despite there being a chain installed and being served.

When server **is not running** it works correctly, and it says:

installed holochains: 
     clutter QmfQVEwca41hPJfKuKfJwQn7ABkD8uMf3USr4FgGfGhf6P

In other words, hc status not working when running a server.

**Comment by timotree3** [comment]
I can't reproduce this.

Version information:
```
$ hc -v
hc version 0.0.5 (holochain 11)
$ uname -rom
4.10.0-21-generic x86_64 GNU/Linux
$ lsb_release -rc
Release:        17.04
Codename:       zesty
```

**Comment by timotree3** [comment]
After @zippy also couldn't reproduce this, I'm gonna consider it fixed.
