### ISSUE TITLE
Generating a holochain twice creates an error

### ISSUE THREAD

**Issue by chrislarcombe** [metacurrency/holochain#71]
chris@Yummy:~/.holochain/clutter$ hc gen chain clutter
Genesis entries added and DNA hashed for new holochain with ID: Qmao4RcFWhcCLjbAx2Ed24JNrS55FMhQfv19J3GKgYBnNZ

and then.....

`chris@Yummy:~/.holochain/clutter$ hc gen chain clutter
panic: cleanup after failed gen not implemented!  Error was: holochain: chain already started

goroutine 1 [running]:
panic(0xda0820, 0xc4202f3630)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/metacurrency/holochain.(*Holochain).GenChain.func1(0xc4202b6978)
	/home/chris/go/src/github.com/metacurrency/holochain/holochain.go:382 +0xcb
github.com/metacurrency/holochain.(*Holochain).GenChain(0xc42029cfc0, 0x0, 0x0, 0x0, 0x13dd420, 0xc4202f3620)
	/home/chris/go/src/github.com/metacurrency/holochain/holochain.go:389 +0x9c9
main.setupApp.func4(0xc4202952c0, 0x0, 0xc4202952c0)
	/home/chris/go/src/github.com/metacurrency/holochain/cmd/hc/hc.go:177 +0x10c
github.com/urfave/cli.HandleAction(0xdbb9e0, 0xc420271610, 0xc4202952c0, 0xc42027eb00, 0x0)
	/home/chris/go/src/github.com/urfave/cli/app.go:485 +0xd4
github.com/urfave/cli.Command.Run(0xf06383, 0x5, 0x0, 0x0, 0xc4202716d0, 0x1, 0x1, 0xf32277, 0x3b, 0x0, ...)
	/home/chris/go/src/github.com/urfave/cli/command.go:207 +0xb96
github.com/urfave/cli.(*App).RunAsSubcommand(0xc42005cea0, 0xc420294f00, 0x0, 0x0)
	/home/chris/go/src/github.com/urfave/cli/app.go:374 +0xb1a
github.com/urfave/cli.Command.startApp(0xf04ef6, 0x3, 0x0, 0x0, 0xc4202716c0, 0x1, 0x1, 0xf30bd5, 0x37, 0x0, ...)
	/home/chris/go/src/github.com/urfave/cli/command.go:293 +0x8a4
github.com/urfave/cli.Command.Run(0xf04ef6, 0x3, 0x0, 0x0, 0xc4202716c0, 0x1, 0x1, 0xf30bd5, 0x37, 0x0, ...)
	/home/chris/go/src/github.com/urfave/cli/command.go:93 +0x16a5
github.com/urfave/cli.(*App).Run(0xc42005cd00, 0xc42000c300, 0x4, 0x4, 0x0, 0x0)
	/home/chris/go/src/github.com/urfave/cli/app.go:250 +0x812
main.main()
	/home/chris/go/src/github.com/metacurrency/holochain/cmd/hc/hc.go:406 +0x57
chris@Yummy:~/.holochain/clutter$ hc status
installed holochains: 
     clutter Qmao4RcFWhcCLjbAx2Ed24JNrS55FMhQfv19J3GKgYBnNZ
`

**Comment by zippy** [comment]
fixed
