### ISSUE TITLE
move expose from code to dna file

### ISSUE THREAD

**Issue by zippy** [metacurrency/holochain#80]
currently exposing requires running the nucleus which is goofy

**Comment by artbrock** [comment]
However, it sure is easier to expose your functions where you write your functions than to remember to go add them to the DNA. I'm not sold on this one yet. Maybe we can come up with  a more compressed format for all the DNA enumeration that would make this simpler?

**Comment by zippy** [comment]
do #100 at the same time so as to only make one breaking change.
