### ISSUE TITLE
document docker development process for chains

### ISSUE THREAD

**Issue by christopherreay** [metacurrency/holochain#90]
including spinning up multiple instances.

What about automated testing for multiple instances? Discuss

**Comment by christopherreay** [comment]
this is now in proper progress. the docs are good and clear. 

I'm updating a whole bunch of scripts in holoskel so that it behaves in a way that someone with mild js knowledge, not a sysadmin, would be able to use it comfortably.

it seems the most obvious general solution to the issue of needing windows developer stuffs is to have a little admin docker container that manages the projects being developed on a box. this should extend nicely to managing the projects installed for an end user

**Comment by zippy** [comment]
closing this as other tickets seem to have superceeded it.
