### ISSUE TITLE
Holochain CLI (eg `hc test`) should return non-zero exit code on failure

### ISSUE THREAD

**Issue by harlantwood** [metacurrency/holochain#93]
eg on Travis I got:

```
$ hc --debug --verbose clone --force . teh
app version: 0.0.2; Holochain lib version %!s(int=2)
Error: DNA not found

 command "hc --debug --verbose clone --force . teh" exited with 0.
```

From https://travis-ci.org/CoMakery/teh/builds/209265163#L110

**Comment by harlantwood** [comment]
This is also true of the `hc test` command -- so when my tests fail on CI, the build is still green!

Eg 

```
failed! m(
=====================
==================================================================
		+++++ 2 test(s) failed :( +++++
==================================================================
Error: 
Test: trust_atom_test:0
	Expected:	%!h(MISSING)%!
(MISSING)	Got Error:		TypeError: HolochainError: commit expected string as second argument is not a function
Test: trust_atom_test:1
	Expected:	%!h(MISSING)%!
(MISSING)	Got Error:		TypeError: HolochainError: commit expected string as second argument is not a function
The command "hc --debug --verbose test teh" exited with 0.
```

From:
https://travis-ci.org/CoMakery/teh/builds/210217149

**Comment by dukejones** [comment]
Merged into `dev` branch

**Comment by harlantwood** [comment]
Looks good on dev branch, eg: 

![screen shot 2017-03-13 at 1 20 52 am](https://cloud.githubusercontent.com/assets/38769/23846601/7050bde2-078b-11e7-8412-31571de33076.png)

-- from https://travis-ci.org/CoMakery/teh/builds/210476124

**Comment by harlantwood** [comment]
And failing tests causing red build as expected: https://travis-ci.org/CoMakery/teh/builds/210481269
