### ISSUE TITLE
Doing putmeta(...) just after put(...) fails

### ISSUE THREAD

**Issue by harlantwood** [metacurrency/holochain#97]
**From @jacksenechal in slack:**

we figured out why the putmeta calls aren't working. There's a delay between the return of put() and the put actually happening on the DHT, so doing a putmeta() right after fails. @zippy is pondering the best way to address it.

...

I was able to get **[teh](https://github.com/CoMakery/teh)** working and use the trust-get command to pull results via the meta-data. I employed a horrible hack to do it, but it's enough to prove the concept and see it working! https://github.com/jacksenechal/holochain/commit/e932837b5685ccb0be20b8e1cce20da6f09018f9

**Jack's commit comment:**

...so you can call `put(x); putmeta(x, ...)` sequentially in JS zomes.
Without this we're seeing the putmeta request fail because the previous
put hasn't gone through to the DHT. This demonstrates the nature of the
bug, but a real fix would probably look like either:

1. Taking an optional callback function or function name as a second arg
   to put(), and calling that when the put has gone through to the DHT
2. Making put() syncronous, blocking further JS execution until it's
   complete.

**Comment by harlantwood** [comment]
@zippy is this a JS or Go level issue?  Do we have tests in the go test suite that show that we do not have this issue at the go level?

**Comment by zippy** [comment]
This is actually at a deeper level of what to expect in the distributed DHT context about what has happened when.  We are working on the right support for how to handle this.  We may be able to make it "pseudo synchronous" because you can issue the actions to your own DHT.  But on top of this, it relates to possibly adding an implicit commit of a special type to your local chain on every put-meta that is kind of like your own claim to having made that put-meta so the DNA can validate off that claim.  More soon.

**Comment by harlantwood** [comment]
Excellent, thanks for your deep arch thinking here. 👍

**Comment by harlantwood** [comment]
Until this is fixed the "right" way, I'm maintaining a "sleep" branch on origin which adds Jack's sleep hack https://github.com/jacksenechal/holochain/commit/e932837b5685ccb0be20b8e1cce20da6f09018f9 .  We're running trust exchange from that holochain sleep branch and it works fine for now.

**Comment by timotree3** [comment]
@harlantwood 
Does JS have it's own sleep function that you could use between `put()` and `putmeta()`?

**Comment by harlantwood** [comment]
Sure, it has setTimeout...  That might work.  @jacksenechal did you do it in the server for a specific reason?

**Comment by jacksenechal** [comment]
The Otto JS VM doesn't actually have any timer functions. I took a shot at hacking in the ottoext package which provides an even loop, but didn't get it to do anything. Others more proficient in Go may fair better. https://github.com/deoxxa/ottoext

**Comment by zippy** [comment]
This has temporarily been fixed by making the puts synchronous (as of 1106e4152fa08a3cd)  This is not a permanent solution, as in general it can't be guaranteed, but we'll bring back asynchronous puts when we provide app developers tools to handle them.

**Comment by zippy** [comment]
This ticket is being superseded by #158
